### PR TITLE
Fix JSON column UTF-8 twice encoded

### LINKED ISSUE #119: Json colums are double encoded
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 2.0.5
| PHP version          | 8.1.0
| Database             | MySQL / PostgreSQL / SQLite / Other

#### Summary

Json diffs are encoded twice. At the end it doesn't show correctly in viewer
image

#### Current behavior

Message in viewer encoded twice 
```
"\u041f\u0420\u0418\u041c\u0415\u0420"
```

#### How to reproduce

- Create entity with JSON column
- Fill something in entity, that can be encoded with UTF-8, for example, `ПРИМЕР`
- Save entity

#### Expected behavior
I see `ПРИМЕР` in viewer

### PR DESCRIPTION
**Pull request by dmitryuk**
Closes #119

### CODE REVIEW

File: src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php [hunk 1]
```diff
@@ -163,7 +166,7 @@ private function diff(EntityManagerInterface $entityManager, object $entity, arr
             } elseif (
                 $meta->hasAssociation($fieldName)
                 && $meta->isSingleValuedAssociation($fieldName)
-                && $this->provider->isAuditedField($entity, $fieldName)
+                && ($isAuditedField ?? $this->provider->isAuditedField($entity, $fieldName))
```
Comment (dmitryuk) [inline src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php:169]: Little-bit performance fix

File: src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php [hunk 2]
```diff
@@ -163,7 +166,7 @@ private function diff(EntityManagerInterface $entityManager, object $entity, arr
...
             ) {
```
Comment (DamienHarper) [inline src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php:170]: @dmitryuk this does work but I don't like assignments in conditions, I find them less readable.

Please, move this assignment above the `if` and refer to the relevant variable both in the `if` and `elseif` conditions.


```php
           $isAuditedField = $this->provider->isAuditedField($entity, $fieldName);

           if (
                 !isset($meta->embeddedClasses[$fieldName])
                 && $meta->hasField($fieldName)
                 && $isAuditedField
             ) {
                 $mapping = $meta->fieldMappings[$fieldName];
                 $type = Type::getType($mapping['type']);
                $o = $this->value($entityManager, $type, $old);
                $n = $this->value($entityManager, $type, $new);
             } elseif (
                 $meta->hasAssociation($fieldName)
                 && $meta->isSingleValuedAssociation($fieldName)
                 && $isAuditedField
             ) {
  
```

**Review by DamienHarper — CHANGES_REQUESTED** [review]

**Comment by DamienHarper** [comment]
@dmitryuk good point, thank you!

File: src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php (hunk 2 above)
Comment (dmitryuk) [reply src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php:170]: I can do it, but the variable $isAuditedField will evaluated in any case even other subconditions returned ’ false’. 
In my solution it doesn't happen

Comment (dmitryuk) [reply src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php]: @DamienHarper I have reverted these lines, because I think we can cache whole conditions using Doctrine cache and speedup much. Will do it in separate PR.

**Review by DamienHarper — APPROVED** [review]
