### PR TITLE
BackedEnum could not be converted to int

### LINKED ISSUE #115: BackedEnum could not be converted to int
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 2.0.5
| PHP version          | 8.1.2
| Database             | MySQL

#### Summary

ErrorException

Warning: Object of class App\Enum\ProductType could not be converted to int

#### Current behavior

`vendor\damienharper\auditor\src\Provider\Doctrine\Auditing\Transaction\AuditTrait.php&line=89#line89)(line 89)`

https://github.com/DamienHarper/auditor/blob/master/src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php#L88

#### Current code
````
case DoctrineHelper::getDoctrineType('INTEGER'):
case DoctrineHelper::getDoctrineType('SMALLINT'):
$convertedValue = (int) $value; // @phpstan-ignore-line
break;
````
Bug fixed
````
case DoctrineHelper::getDoctrineType('INTEGER'):
case DoctrineHelper::getDoctrineType('SMALLINT'):
$convertedValue = (int) $value instanceof \BackedEnum ? $value->value : $value ; // @phpstan-ignore-line
break;
````

### PR DESCRIPTION
**Pull request by dmitryuk**
Closes #115

### CODE REVIEW

**Comment by dmitryuk** [comment]
I didn't fixed some cs-fixer errors of files I have not touched.

**Comment by DamienHarper** [comment]
@dmitryuk thanks for the contrib, much appreciated.

File: tests/Provider/Doctrine/Issues/Issue115Test.php [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+ *
+ * @small
+ */
+final class Issue115Test extends TestCase
+{
+    use DefaultSchemaSetupTrait;
+
+    public function testIssue115(): void
+    {
+        if (\PHP_VERSION_ID < 80000) {
```
Comment (DamienHarper) [inline tests/Provider/Doctrine/Issues/Issue115Test.php:29]: `BackedEnum` are only available in PHP >= 8.1.0 (see https://php.watch/versions/8.1)

File: src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php [hunk 2]
```diff
@@ -75,6 +76,10 @@ private function value(EntityManagerInterface $entityManager, Type $type, $value
             return null;
         }
 
+        if ($value instanceof BackedEnum) {
```
Comment (DamienHarper) [inline src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php:79]: I'd double check PHP version + remove the `use` statement line 7 + use the FQCN here (`\BackedEnum`) here in the test

**Review by DamienHarper — CHANGES_REQUESTED** [review]

File: tests/Provider/Doctrine/Issues/Issue115Test.php (hunk 1 above)
Comment (dmitryuk) [reply tests/Provider/Doctrine/Issues/Issue115Test.php]: Done

File: src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php (hunk 2 above)
Comment (dmitryuk) [reply src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php]: Added double check and FQCN, but previously I run php-cs-fixer that removed leading slash

Comment (dmitryuk) [reply src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php]: @DamienHarper should I run cs-fixer? It will remove FQCN for BackedEnum and will touch some lines I never changed

Comment (DamienHarper) [reply src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php]: You're right, let csfixer fix the file and commit it back. It shouldn't be problematic since you previously check PHP version. That way, it should go further in the CI pipeline (will still fail with PHPStan and PHP 7.4 but that's another story :))

Comment (dmitryuk) [reply src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php]: cs-fixer done

**Review by DamienHarper — CHANGES_REQUESTED** [review]
As long as `enum` keyword is available in PHP >= 8.1.0 only, and PHPStan not being able to ignore lines conditionally, I think it worth:
1. duplicating `phpstan.neon` file to `phpstan-74.neon` and `phpstan-80.neon` for example and tailor them to ignore relevant files
2. Update CI (`.github/workflows/ci-2x.yml` file) to use the relevant PHPStan config file regarding PHP version used.

That should fix current issues with CI. You could even revert your latest commits about PHPstan, they should not be required if PHPStan uses dedicated config files per PHP version.

File: tests/Provider/Doctrine/Issues/Issue115Test.php [hunk 3]
```diff
@@ -19,16 +19,15 @@
...
  */
 final class Issue115Test extends TestCase
 {
     use DefaultSchemaSetupTrait;
 
     public function testIssue115(): void
     {
-        if (\PHP_VERSION_ID < 81000) {
-            self::markTestSkipped('PHP > 8.1 is required.');
-        }
```
Comment (DamienHarper) [inline tests/Provider/Doctrine/Issues/Issue115Test.php]: you should keep this, the solution I talked previously only concerns PHPStan, these instructions are related to PHPUnit

**Review by DamienHarper — CHANGES_REQUESTED** [review]

File: tests/Provider/Doctrine/Issues/Issue115Test.php (hunk 3 above)
Comment (dmitryuk) [reply tests/Provider/Doctrine/Issues/Issue115Test.php]: Impossible to use this syntax because on runtime I got Syntax error with enums
I used another way https://phpunit.readthedocs.io/en/9.5/incomplete-and-skipped-tests.html

Comment (dmitryuk) [reply tests/Provider/Doctrine/Issues/Issue115Test.php]: https://github.com/DamienHarper/auditor/actions/runs/3328237934/jobs/5504011752

File: src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php [hunk 4]
```diff
@@ -74,6 +75,9 @@ private function value(EntityManagerInterface $entityManager, Type $type, $value
         if (null === $value) {
             return null;
         }
+        if (interface_exists(UnitEnum::class) && $value instanceof UnitEnum && property_exists($value, 'value')) {
```
Comment (dmitryuk) [inline src/Provider/Doctrine/Auditing/Transaction/AuditTrait.php:78]: Removed PHP_version check, because there is other enough checks

**Review by DamienHarper — APPROVED** [review]

**Comment by DamienHarper** [comment]
Thanks again @dmitryuk
